# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: validateTerraform
  displayName: Validating Terraform code
  jobs:
  - job: 
    steps:
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'Azure-AKS-connection'
        backendAzureRmSubscriptionId: '58f627af-5f2f-4f24-b8b3-67712c182a5c'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'Nihal-Training'
        backendAzureRmResourceGroupLocation: 'Australia East'
        backendAzureRmStorageAccountName: 'nihalstorageaccounts'
        backendAzureRmContainerName: 'terraformremotestate'
        allowTelemetryCollection: true